# Generated by Django 2.1 on 2018-09-10 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reaction',
            field=models.ManyToManyField(blank=True, related_name='user_reaction_for_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
