# Generated by Django 2.1 on 2018-09-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favorite_posts',
            field=models.ManyToManyField(to='mainApp.Post'),
        ),
    ]
